config/routes.rb
Rails.application.routes.draw do
  root 'products#index'

  #Route redefinitions
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  controller :users do 
    get 'favorites' => :show
  end

  resources :users, only: [:new, :create, :show]

  resources :products, only: [:index, :new, :create]

  resources :products do
    put :favorite, on: :member
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite_product.rb
class FavoriteProduct < ApplicationRecord
	belongs_to :product
  	belongs_to :user
end

app/models/product.rb
class Product < ApplicationRecord
	validates :name, presence: true, uniqueness: true
	validates :description, presence: true
	validates :price, presence: true, numericality: { greater_than: 0 }

	validates :image_url, allow_blank: true, format: {
        with: %r{\.(gif|jpg|png)\z}i
    }

    has_many :favorite_products 
  	has_many :favorited_by, :through => :favorite_products, :source => :user
end

app/models/user.rb
class User < ApplicationRecord
	validates :name, presence: true
	validates :username, presence: true, uniqueness: true

	has_secure_password

	has_many :products

	has_many :favorite_products
  	has_many :favorites, :through => :favorite_products, :source => :product
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	helper_method :current_user
	helper_method :logged_in?
	
	#Auxiliar method to find the instance of the logged user.
	def current_user
   		User.find_by(id: session[:user_id])
	end

	#Auxiliar method that checks if a user is logged in. It's not really necessary, but helps to not be confused.
	def logged_in?
    	!current_user.nil?
	end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	#Avoids the adding of favorites if there is no user logged.
	before_action :authorize, only: :favorite

	def index
		@products = Product.all.order(:name) 
	end

	def new
		@product = Product.new
	end

	def create
		@product = Product.new(product_params)
		
		#Permits to keep the web running even if it was intended to add a product completely empty. Does not save anything
		#in the database.
		if @product.save
      redirect_to root_path
    else
      render :new
    end

	end

	def favorite
		@product = Product.find(params[:id])
    
    type = params[:type]
    
    #Checks if the product is going to be added to the favorites list or not
    if type == "favorite"

    	#Checks if the product was already set as a favorite. Avoids having multiple displays of the same object.
    	if !current_user.favorites.exists?(@product.id)
      	current_user.favorites << @product
      	redirect_to '/', notice: "You added #{@product.name} to your favorites list!"
      else
      	redirect_to '/', notice: "That product is already in your favorites list!"
      end

    #In case that the type was set to "unfavorite" this will destroy the association between the user and the product
    #previously added into his favorite list. Notice that the instance of the product will not be deleted from the database.
    else type == "unfavorite"
      current_user.favorites.delete(@product)
      redirect_to current_user, notice: "You removed #{@product.name} from your favorites list!"
    end
  end

	private
    def product_params
      params.require(:product).permit(:name, :description, :image_url, :price)
    end

  #Auxilir method to authorize only logged users to enter certain roots
	def authorize
		if !logged_in?
			redirect_to root_path
		end
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	#Avoids the login view to be displayed if an user is logged.
	before_action :authorize, only: :new

	def new
	end

	#Creates an unique session. It will not be followed by any other until this one is destroyed
	def create
		@user = User.find_by(username: params[:username])
   		if @user && @user.authenticate(params[:password])
      		session[:user_id] = @user.id

      		redirect_to root_path, notice: "Logged in succesfully"
   		else
      		redirect_to '/login', notice: "Wrong Username and/or Password"
   		end
	end

	def destroy
		session.delete(:user_id)
    	redirect_to root_path
	end

	private

	#Auxilir method to authorize only logged users to enter certain roots
	def authorize
		if logged_in?
			redirect_to root_path
		end
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	#Avoids the favorite product list view to be displayed if an user is not logged.
	before_action :authorize, only: :show

	def new
	end

	def create
		@user = User.new(user_params)

		respond_to do |format|
			if @user.save
				format.html { redirect_to login_url, notice: "User #{@user.name} was successfully created." }
			else 
				format.html { render :new, notice: "There was a processing error." }
			end
		end
	end

	def show
		@user = current_user
	end

	private

	def user_params
		params.permit(:name, :username, :password, :favorites)
	end

	#Auxilir method to authorize only logged users to enter certain roots
	def authorize
		if !logged_in?
			redirect_to root_path
		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TiendaCDS</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- Bootstrap stuff -->
    <link rel="stylesheet" type="text/css" href="bootstrap.css"> 
    <link rel="stylesheet" type="text/css" href="custom.css">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <h1 class = "display-1">TiendaCDS</h1>
    </header>

    <section>
      <!-- 
        Sidebar of the website. Shows certain bar elements depending on the status of the session 
        (if there is a logged user or not). 
      -->
      <nav class="nav flex-column navbar-expand-lg navbar-dark bg-dark">
        <ul>
          <li class="navbar-brand"><%= link_to 'Products', root_path %></a></li>

          <% if !logged_in? %>
            <li class="navbar-brand"><%= link_to 'Login', login_path %></li>
          <% end %>

          <% if logged_in? %>
            <li class="navbar-brand"><%= link_to 'My Favorites', favorites_path %></li>
          <% end %>

          <li class="navbar-brand"><%= link_to 'Signup', new_user_path %></li>
          
          <% if logged_in? %>
            <li class="navbar-brand"><%= link_to 'Logout', logout_path, method: "delete" %></li>
          <% end %>
        </ul>

        <% if logged_in? %>
          <p class = "navbar-text" style="color: white;">You are Logged In, <%= current_user.name %></p>
        <% end %>
      </nav>

      <!--
        Alerts that will only be displayed upon mistakes, or bad handling of website pages.
      -->
      <% flash.each do |type, msg| %>
        <div>
          <%= msg %>
        </div>
      <% end %>

      <main>
        <%= yield %>
      </main>
    </section>

    <!-- Another bootstrap thing -->
    <script src="javascript/bootstrap.js"></script>


  </body>
</html>

app/views/products/index.html.erb
<h1>Products</h1>

<table class="table table-image">

  <!-- Option displayed to allow users the creation of a new product -->
  <tfoot>
    <tr>
      <td style= "text-align: center; " colspan="3">
        <%= button_to 'New Product + ', new_product_path, method: "get" %>
      </td>
    </tr>
  </tfoot>
  
  <!-- Table view -->
  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td style="text-align: center;">
          <div class="img-fluid"><%= image_tag(product.image_url) %></div>
        </td>

        <td style="margin-right: 20px;">
          <h3 style="text-decoration: underline;"><%= product.name %></h3>

          <p style="margin-left= 20px;">
            <%= product.description %>
          </p>

          <p>
            PRICE: <%= product.price %> USD
          </p>

          <p>
            <%= button_to 'Add to Favorites', favorite_product_path(product, type: "favorite"), method: :put %>
          </p>
          
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/products/new.html.erb
<!--
  Creates a product upon submit
-->

<h1 style="margin-bottom: 20px;">New Product</h1>

<%= form_with model: @product do |form| %>
  <div>
    <p class = "form-label" ><%= form.label 'Name:' %></p>
    <p class = "form-control-plaintext"><%= form.text_field :name %></p>
  </div>

  <div>
    <p class = "form-label" ><%= form.label 'Description:' %></p>
    <p class="form-control-plaintext"><%= form.text_area :description%></p>
  </div>

  <div>
    <%= form.label 'Image:' %>
    <p class="form-control-plaintext"><%= form.text_field :image_url %></p>
  </div>

  <div>
    <%= form.label 'Price:' %>
    <p class="form-control-plaintext"><%= form.number_field :price %></p>
  </div>

  <div>
    <%= form.submit 'Add Product' %>
  </div>
<% end %>

app/views/users/new.html.erb
<h1 style="margin-bottom: 20px;"> Sign Up </h1>

 <%= form_tag users_path, method: 'POST' do %>
   <div>
      <p class = "form-label" >Name: </p>
      <p class = "form-control-plaintext" ><%= text_field_tag(:name) %></p>

      <p class = "form-label" >Username: </p>
      <p class = "form-control-plaintext" ><%= text_field_tag(:username) %></p>

      <p class = "form-label" >Password: </p>
      <p class = "form-control-plaintext"><%= password_field_tag(:password) %> </p>
   </div>

   <div>
    <%= submit_tag  'Register' %>
   </div>
<% end %>

app/views/users/show.html.erb
<h1> My Favorites </h1>

  <table class="table table-image">
  <tbody>

    <!-- 
      "x" represents each product. It was not written that way to prevent confusions with the product's instances outside 
      the favorite related associations.
    -->
    <% current_user.favorites.each do |x| %>
      <tr>
        <td style= "text-align: center; " colspan="3">
          <div class="img-fluid"><%= image_tag(x.image_url) %></div>
        </td>

        <td>
          <h3 style="text-decoration: underline;"><%= x.name %></h3>

          <p style="margin-left= 20px;">
            <%= x.description %>
          </p>

          <p>
            PRICE: <%= x.price %> USD
          </p>

          <p>
            <%= button_to 'Remove from favorites', favorite_product_path(x, type: "unfavorite"), method: :put %>
          </p>
          
        </td>
      </tr>
    <% end %>
  </tbody>
</table>